import type { Metadata } from 'next';
import { Barlow_Condensed, Montserrat } from 'next/font/google';
import '../sass/globals.scss';
import { ContextProvider } from '../contexts/app.context';
import { Header } from '@/components/Header/Header';
import { Footer } from '@/components/Footer/Footer';

const mainFont = Montserrat({
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
	variable: '--font-montserrat',
});

const headingFont = Barlow_Condensed({
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
	variable: '--font-barlow',
});

export const metadata: Metadata = {
	title: 'Działki w Beskidzie Żywieckim',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pl' className={`${mainFont.variable} ${headingFont.variable}`}>
			<body className={mainFont.className}>
				<ContextProvider>
					<Header/>
					{children}
					<Footer/>
				</ContextProvider>
			</body>
		</html>
	);
}
